# Generated by Django 5.0.6 on 2024-08-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_meal_bookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='idMEAL',
            new_name='meal_id',
        ),
    ]
